# Generated by Django 5.0.3 on 2024-03-19 14:46

from datetime import timedelta
import json
import os
from sqlite3 import IntegrityError
from django.db import migrations, transaction

def put_initial_data(apps, schema_editor):
    Travel = apps.get_model('travels', 'Travel')

    file_path = os.path.dirname(os.path.realpath(__file__))
    file = open(os.path.join(file_path, '../../../../data.json'), 'r')
    data = json.load(file)

    for travel in data['transport']:
        with transaction.atomic():
            Travel.objects.create(
                name=travel['name'],
                price_confort=travel['price_confort'][3:],
                price_econ=travel['price_econ'][3:],
                city=travel['city'],
                duration=timedelta(hours=int(travel['duration'].rstrip('h'))),
                seat=travel['seat'],
                bed=travel['bed']
            )



class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(put_initial_data),
    ]
